/**
 * @author Nick Mosher <nicholastmosher@gmail.com>
 */
export const PlanActionTypes = {
  CREATE_PLAN: 'CREATE_PLAN',
  RENAME_PLAN: 'RENAME_PLAN',
  SELECT_PLAN: 'SELECT_PLAN',
  ADD_COLLABORATOR: 'ADD_COLLABORATOR',
  REMOVE_COLLABORATOR: 'REMOVE_COLLABORATOR',
  EDIT_COLLABORATOR: 'EDIT_COLLABORATOR',
  CHANGE_OWNER: 'CHANGE_OWNER',
  UPDATE_LAST_TRANSACTION: 'UPDATE_LAST_TRANSACTION',
};
